//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by bookey.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_ABOUTBOX                    101
#define IDD_BOOKEY_FORM                 102
#define IDS_REGISTER                    102
#define IDD_BOOKEY_DIALOG               103
#define IDS_DELETE                      103
#define IDS_SYNCHRONIZE                 104
#define IDS_REGISTER4                   105
#define IDS_DIRECTION                   106
#define IDS_DOUBLE_DIRECTION            107
#define IDS_MENU_TURN_ON                108
#define IDS_MENU_TURN_OFF               109
#define IDS_MENU_PASTE                  110
#define IDS_BTN_PUT_BOOKMARKS           111
#define IDS_BTN_SAVE_BOOKMARKS          112
#define IDS_BTN_IMPORT_A                113
#define IDS_BTN_IMPORT_AB               114
#define IDS_MENU_TURN_ON2               115
#define IDS_MENU_TURN_OFF2              116
#define IDR_MAINFRAME                   128
#define IDR_BOOKEYTYPE                  129
#define IDS_ABOUT_SUPPORT               129
#define IDD_DELETE_DIALOG               130
#define IDS_ABOUT_COMMUNITY             130
#define IDD_DELETE_DIALOG2              131
#define IDS_ABOUT_COMMUNITY2            131
#define IDD_DELETE_DIALOG3              132
#define IDS_ABOUT_SUPPORT2              132
#define IDD_DELETE_DIALOG4              133
#define IDS_MANAGE_BOOKMARKS            133
#define IDD_SYNC_DIALOG                 134
#define IDS_EDIT_SETTING                134
#define IDD_EDIT_BOOKMARK_DIALOG        135
#define IDD_REGISTER_BOOKMARK_DIALOG    136
#define IDD_PROCEEDING_DIALOG           137
#define IDB_BITMAP_HATENA_BOOKMARK      139
#define IDB_BITMAP_DRECOM_RSS           140
#define IDB_BITMAP_DELICIOUS            141
#define IDB_BITMAP_FLOG                 142
#define IDB_BITMAP_MM_MEMO              143
#define IDC_HAND2                       148
#define IDB_BITMAP_LIVEDOOR_CLIP        151
#define IDB_BITMAP_ECNAVI_CLIP          152
#define IDB_BITMAP_NIFTY_CLIP           153
#define IDB_BITMAP_1470NET              154
#define IDD_SETTING_DIALOG              155
#define IDD_TAB_HATENA                  156
#define IDD_TAB_DELICIOUS               157
#define IDD_TAB_LIVEDOOR                158
#define IDD_TAB_NIFTY                   159
#define IDD_TAB_ECNAVI                  160
#define IDB_BITMAP_NEWSING              160
#define IDD_TAB_FLOG                    161
#define IDB_BITMAP_POOKMARK             161
#define IDD_TAB_DRECOM                  162
#define IDB_BITMAP_BLUEDOT              162
#define IDB_BITMAP_JOLTMARK             163
#define IDD_TAB_MMMEMO                  164
#define IDD_TAB_1470NET                 165
#define IDD_TAB_NEWSING                 166
#define IDB_BITMAP_BLOGPET              166
#define IDD_TAB_POOKMARK                167
#define IDD_TAB_BLUEDOT                 168
#define IDD_TAB_LOCALOPML               169
#define IDD_TAB_JOLTMARK                170
#define IDD_TAB_BLOGPET                 171
#define IDD_DELETE_TAGS_DIALOG          172
#define IDD_REPLACE_TAGS_DIALOG         173
#define IDD_DIALOG_PROXY_INFO           174
#define IDB_BITMAP_FC2BOOKMARK          174
#define IDD_TAB_FC2BOOKMARK             175
#define IDB_BITMAP_TWITTER              175
#define IDD_TAB_TWITTER                 176
#define IDB_BITMAP_YJBOOKMARK           176
#define IDD_TAB_YJ_BOOKMARK             177
#define IDB_YAHOO_BOOKMARK              177
#define IDD_TAB_YAHOO_BOOKMARKS         179
#define IDD_TAB_TIMELOG                 180
#define IDB_BITMAP_TIMELOG              181
#define IDD_CAPTCHA_DIALOG              182
#define IDB_BITMAP_CAPTCHA              183
#define IDD_TAB_DIGG                    183
#define IDB_BITMAP_DIGG                 184
#define IDD_TAB_TUMBLR                  184
#define IDD_TAB_DIIGO                   185
#define IDD_BLOGID_DIALOG               186
#define IDB_BITMAP_HATENA_STAR          187
#define IDB_BITMAP_TUMBLR               188
#define IDB_BITMAP_DIIGO                191
#define IDD_INPUT_PIN                   192
#define IDC_COMBO_BOOKMARK2             1000
#define IDC_COMBO_BOOKMARK1             1001
#define IDC_EDIT_USERNAME1              1002
#define IDC_EDIT_USERNAME2              1003
#define IDC_EDIT_PASSWORD1              1004
#define IDC_EDIT_PASSWORD2              1005
#define IDC_BUTTON_GET                  1006
#define IDC_BUTTON_PUT                  1007
#define IDC_BUTTON_SYNC                 1008
#define IDC_BUTTON_DELETE               1009
#define IDC_BUTTON_DELETE_HATENA        1009
#define IDC_BUTTON_DELETE_DELICIOUS     1010
#define IDC_BUTTON_REGISTER             1010
#define IDC_BUTTON_EDIT_TAGS            1010
#define IDC_DESCRIPTION                 1011
#define IDC_BUTTON_DELETE_MMMEMO        1011
#define IDC_BUTTON_DELETE_TAGS          1011
#define IDC_EDIT_USERNAME               1012
#define IDC_BUTTON_DELETE_BPTAGS        1012
#define IDC_EDIT_PASSWORD               1013
#define IDC_BUTTON_DELETE_YES           1013
#define IDC_BUTTON_DELETE_DRECOMRSS     1013
#define IDC_LIST_BLOGID                 1013
#define IDC_BUTTON_DELETE_NO            1014
#define IDC_BUTTON_DELETE_FLOG          1014
#define IDC_EDIT_YJ_USERNAME            1014
#define IDC_EDIT_APIKEY                 1014
#define IDC_EDIT_BLOGNAME               1014
#define IDC_EDIT_BM_URL                 1015
#define IDC_BUTTON_DELETE_LIVEDOORCLIP  1015
#define IDC_EDIT_YJ_PASSWORD            1015
#define IDC_EDIT_BM_TITLE               1016
#define IDC_BUTTON_SYNC1                1016
#define IDC_BUTTON_DELETE_ECNAVI        1016
#define IDC_EDIT_BM_COMMENT             1017
#define IDC_BUTTON_SYNC2                1017
#define IDC_BUTTON_DELETE_NIFTYCLIP     1017
#define IDC_EDIT_BM_TAGS                1018
#define IDC_BUTTON_SYNC3                1018
#define IDC_QUERY_MESSAGE               1019
#define IDC_BUTTON_DELETE_FORCELY       1020
#define IDC_BUTTON_SETTING              1021
#define IDC_BUTTON_BACKWORD             1021
#define IDC_BUTTON_FINISH               1022
#define IDC_BUTTON_TOOL                 1023
#define IDC_COUNTER                     1024
#define IDC_CHECK_TIPJAR                1025
#define IDC_STATIC_EXECUTING            1026
#define IDC_STATIC_PROCEED_STRING       1027
#define IDC_TAG001                      1028
#define IDC_TAG002                      1029
#define IDC_BM1                         1029
#define IDC_TAG003                      1030
#define IDC_BM2                         1030
#define IDC_TAG004                      1031
#define IDC_BMNAMES                     1031
#define IDC_TAG005                      1032
#define IDC_CHECK_TAG_SUGGESTION        1032
#define IDC_TAG006                      1033
#define IDC_CHECK_USERS                 1033
#define IDC_TAG007                      1034
#define IDC_CHECK_LANGUAGE              1034
#define IDC_TAG008                      1035
#define IDC_TAG009                      1036
#define IDC_TAG010                      1037
#define IDC_TAG011                      1038
#define IDC_TAG012                      1039
#define IDC_TAG013                      1040
#define IDC_TAG014                      1041
#define IDC_TAG015                      1042
#define IDC_TAG016                      1043
#define IDC_TAG017                      1044
#define IDC_TAG018                      1045
#define IDC_TAG019                      1046
#define IDC_TAG020                      1047
#define IDC_COMBO_CATEGORY              1048
#define IDC_COMBO_CATEGORY2             1049
#define IDC_RADIO_EVAL01                1050
#define IDC_RADIO_EVAL02                1051
#define IDC_RADIO_EVAL03                1052
#define IDC_RADIO_EVAL04                1053
#define IDC_RADIO_EVAL05                1054
#define IDC_STATIC_DRECOM               1055
#define IDC_EDIT_PROXY_SERVER_NAME      1055
#define IDC_STATIC_FLOG                 1056
#define IDC_EDIT_PROXY_PORT_NUMBER      1056
#define IDC_ICON_HATENA_BOOKMARK        1057
#define IDC_EDIT_PROXY_USER_NAME        1057
#define IDC_ICON_DELICIOUS              1058
#define IDC_EDIT_PROXY_PASSWORD         1058
#define IDC_ICON_MM_MEMO                1059
#define IDC_ICON_DRECOM_RSS             1061
#define IDC_ICON_FLOG                   1062
#define IDC_BOOKEY_WEB_URL              1063
#define IDC_RADIO_EVAL00                1063
#define IDC_BOOKEY_MAIL_ADDR            1064
#define IDC_HB_USERS                    1065
#define IDC_DELICIOUS_USERS             1066
#define IDC_MM_USERS                    1067
#define IDC_ICON_LIVEDOOR               1068
#define IDC_ECNAVI_USERS                1069
#define IDC_ICON_ECNAVI_CLIP            1070
#define IDC_ICON_NIFTY_CLIP             1071
#define IDC_STATIC_1470NET              1072
#define IDC_ICON_1470NET                1072
#define IDC_LIVEDOORCLIP_USERS          1073
#define IDC_NEWS_GOOD                   1074
#define IDC_NEWS_BAD                    1075
#define IDC_POST_EVAL                   1076
#define IDC_TAB_SETTING                 1077
#define IDC_DIGG_USERS                  1077
#define IDC_HATENA_STAR_USERS           1078
#define IDC_EDIT_HATENA_USERNAME        1079
#define IDC_NIFTYCLIP_USERS             1079
#define IDC_EDIT_HATENA_PASSWORD        1080
#define IDC_RADIO_NOCHANGE              1081
#define IDC_RADIO_CHANGE                1082
#define IDC_RADIO_TARGET                1083
#define IDC_RADIO_NONTARGET             1084
#define IDC_BUTTON_ACCEPT               1084
#define IDC_RADIO_TYPEKEY               1101
#define IDC_RADIO_HATENA                1102
#define IDC_COMBO_DELETELIST            1102
#define IDC_RADIO_TYPEKEY_HATENA        1103
#define IDC_RADIO_HATENA_TYPEKEY        1104
#define IDC_BUTTON_DELETE_INTERACTIVE   1105
#define IDC_BUTTON_DELETE_ALL           1106
#define IDC_ICON_NEWSING                1106
#define IDC_ICON_POOKMARK               1107
#define IDC_ICON_BLUEDOT                1110
#define IDC_BUTTON_GET_TOKEN            1112
#define IDC_EDIT_LOCALOPML_FILENAME     1113
#define IDC_TOKEN_STATUS                1113
#define IDC_BUTTON_FILEOPEN             1114
#define IDC_RADIO_PUBLIC                1115
#define IDC_RADIO_PRIVATE               1116
#define IDC_RADIO_FRIENDS               1117
#define IDC_ICON_JOLTMARK               1118
#define IDC_ICON_BLOGPET                1121
#define IDC_COMBO_DELETELIST_TAGS       1122
#define IDC_BUTTON_GET_TAGS             1123
#define IDC_COMBO_DELETE_TAGLIST        1124
#define IDC_EDIT_NEW_TAG                1125
#define IDC_WAITING                     1126
#define IDC_BUTTON_PROXY                1127
#define IDC_ICON_FC2BOOKMARK            1128
#define IDC_ICON_TWITTER                1133
#define IDC_BOOKEY_VERSION              1134
#define IDC_ICON_YJBOOKMARK             1135
#define IDC_ICON_YAHOO_BOOKMARKS        1142
#define IDC_ICON_TIMELOG                1143
#define IDC_EDIT_CAPTCHA                1144
#define IDC_ICON_DIGG                   1145
#define IDC_COMBO_TOPIC                 1147
#define IDC_BITMAP_CAPTCHA              1148
#define IDC_EDIT_TITLE                  1149
#define IDC_EDIT_COMMENT                1150
#define IDC_ICON_HATENA_STAR            1150
#define IDC_RADIO_USE_ECNAVI            1153
#define IDC_RADIO_USE_YJ                1154
#define IDC_RADIO_USE_NEWSING           1155
#define IDC_ICON_TUMBLR                 1156
#define IDC_ICON_DIIGO                  1157
#define IDC_BUTTON_APIKEY               1158
#define IDC_POWEREDBY_NIFTYCLIP         1159
#define IDC_OPENSSL                     1160
#define IDC_ICONV                       1161
#define IDC_RADIO_BASIC                 1161
#define IDC_CREDIT_YAHOOJAPAN           1162
#define IDC_RADIO_OAUTH                 1162
#define IDC_BUTTON_SELECT_TARGET        1162
#define IDC_EDIT_PIN                    1163
#define IDS_BOOKEY_MAIL_ADDR            57346
#define IDS_BOOKEY_WEB_URL              57347
#define IDS_BOOKEY_VERSION              57348
#define IDS_BOOKEY_RESOURCE_XML         57349
#define IDS_BOOKEY_COMMUNITY            57350
#define IDS_BOOKEY_COMMUNITY2           57351
#define IDS_BOOKEY_SUPPORT              57352
#define IDS_BOOKEY_API_ID               57353
#define IDS_CREDIT_YAHOOJAPAN_URL       57354
#define IDS_TWITTER_OA001               57355
#define IDS_TWITTER_OA002               57356
#define IDS_URL_TWITTER_REQUEST_TOKEN   57357
#define IDS_URL_TWITTER_ACCESS_TOKEN    57358
#define IDS_URL_TWITTER_AUTHORIZE       57359
#define IDS_TWITTER_ALLOW_OAUTH         57360
#define IDS_TWITTER_STOP_OAUTH          57361
#define IDS_FILETYPE_OPML               61296
#define IDS_OPFAIL_OPML                 61297
#define IDS_RDFAIL_OPML                 61298
#define IDS_WRFAIL_OPML                 61299
#define IDS_FILETYPE_HTML               61300
#define IDS_OPFAIL_HTML                 61301
#define IDS_RDFAIL_HTML                 61302
#define IDS_WRFAIL_HTML                 61303
#define IDS_FILETYPE_OPERA_6            61304
#define IDS_OPFAIL_ADR                  61305
#define IDS_RDFAIL_ADR                  61306
#define IDS_WRFAIL_ADR                  61307
#define IDS_FILETYPE_XML                61308
#define IDS_OPFAIL_XML                  61309
#define IDS_RDFAIL_XML                  61310
#define IDS_WRFAIL_XML                  61311
#define IDS_TGT_HATENA_BOOKMARK         61408
#define IDS_TGT_DELICIOUS               61409
#define IDS_TGT_MMMEMO                  61410
#define IDS_TGT_DRECOM_RSS              61413
#define IDS_TGT_FLOG                    61414
#define IDS_TGT_LIVEDOOR_CLIP           61415
#define IDS_TGT_ECNAVI_CLIP             61416
#define IDS_TGT_NIFTY_CLIP              61417
#define IDS_TGT_1470NET                 61418
#define IDS_TGT_NEWSING                 61419
#define IDS_TGT_POOKMARK                61420
#define IDS_TGT_BLUEDOT                 61421
#define IDS_TGT_JOLTMARK                61422
#define IDS_TGT_BLOGPET                 61423
#define IDS_TGT_OPML                    61424
#define IDS_TGT_LOCAL_OPML              61425
#define IDS_TGT_NETSCAPE_1              61426
#define IDS_TGT_OPERA_6                 61427
#define IDS_TGT_HATENA_FEED             61428
#define IDS_TGT_LIVEDOOR_FEED           61429
#define IDS_TGT_FC2_BOOKMARK            61430
#define IDS_TGT_TWITTER                 61431
#define IDS_TGT_DELICIOUS_XML           61432
#define IDS_TGT_YJ_BOOKMARK             61433
#define IDS_TGT_YAHOO_BOOKMARKS         61434
#define IDS_TGT_TIMELOG                 61435
#define IDS_TGT_DIGG                    61436
#define IDS_TGT_HATENA_STAR             61437
#define IDS_TGT_TUMBLR                  61438
#define IDS_TGT_DIIGO                   61439
#define IDS_DSC_HATENA_BOOKMARK         61472
#define IDS_DSC_DELICIOUS               61473
#define IDS_DSC_MMMEMO                  61474
#define IDS_DSC_DRECOM_RSS              61476
#define IDS_DSC_FLOG                    61477
#define IDS_DSC_LIVEDOOR_CLIP           61478
#define IDS_DSC_ECNAVI_CLIP             61479
#define IDS_DSC_NIFTY_CLIP              61480
#define IDS_DSC_1470NET                 61481
#define IDS_DSC_POOKMARK                61482
#define IDS_DSC_BLUEDOT                 61483
#define IDS_DSC_JOLTMARK                61484
#define IDS_DSC_FC2_BOOKMARK            61485
#define IDS_DSC_BLOGPET                 61486
#define IDS_DSC_TWITTER                 61487
#define IDS_DSC_YJBOOKMARK              61488
#define IDS_DSC_YJBOOKMARKS             61488
#define IDS_DSC_YAHOO_BOOKMARK          61489
#define IDS_DSC_YAHOO_BOOKMARKS         61489
#define IDS_DSC_TIMELOG                 61490
#define IDS_DSC_TUMBLR                  61491
#define IDS_DSC_DIGG                    61492
#define IDS_DSC_DIIGO                   61493
#define IDS_TTL_SYNC_TARGET             61500
#define IDS_TXT_SYNC_TARGET             61501
#define IDS_TTL_BROKEN_SETTING          61502
#define IDS_TXT_BROKEN_SETTING          61503
#define IDS_TTL_CANCEL_LOGIN_INFO       61504
#define IDS_TXT_CANCEL_LOGIN_INFO       61505
#define IDS_TTL_CANCEL_PROCEDURE        61506
#define IDS_TXT_CANCEL_PROCEDURE        61507
#define IDS_TTL_EXECUTE_PROCEDURE       61508
#define IDS_TXT_EXECUTE_PROCEDURE       61509
#define IDS_BTN_EXECUTE_PROCEDURE       61510
#define IDS_BTN_EXECUTE_PROCEDURE_ALL   61511
#define IDS_BTN_SKIP_PROCEDURE          61512
#define IDS_BTN_CANCEL_PROCEDURE        61513
#define IDS_TTL_NO_SETTING_LOCAL_OPML   61514
#define IDS_TXT_NO_SETTING_LOCAL_OPML   61515
#define IDS_TTL_SYNCHRONIZE             61516
#define IDS_TXT_SYNCHRONIZE             61517
#define IDS_TXT_START_SYNCHRONIZING     61518
#define IDS_TXT_CONTINUE_SYNCHRONIZING  61519
#define IDS_TXT_NO_SYNCHRONIZING        61520
#define IDS_TXT_END_SYNCHONIZING        61521
#define IDS_TTL_PUT_ALL_BOOKMARKS       61522
#define IDS_TXT_PUT_ALL_BOOKMARKS       61523
#define IDS_TTL_FAILURE_GET_BOOKMARKS_NOT_EXIST 61524
#define IDS_TXT_FAILURE_GET_BOOKMARKS_NOT_EXIST 61525
#define IDS_TTL_FAILURE_GET_BOOKMARKS   61526
#define IDS_TXT_FAILURE_GET_BOOKMARKS   61527
#define IDS_TTL_DELETE_ALL_BOOKMARKS    61528
#define IDS_TXT_DELETE_ALL_BOOKMARKS    61529
#define IDS_TTL_DELETE_ALL              61530
#define IDS_TXT_DELETE_ALL              61531
#define IDS_TXT_CONTINUE_DELETING       61532
#define IDS_TTL_FAILURE_DELETE_BOOKMARKS 61533
#define IDS_TXT_FAILURE_DELETE_BOOKMARKS 61534
#define IDS_TXT_GET_BOOKMARKS           61535
#define IDS_TXT_CONTINUE_GETTING_BOOKMARKS 61536
#define IDS_TXT_CONTINUE_LOGIN          61537
#define IDS_TXT_CONTINUE_GETTING_FOLDER 61538
#define IDS_TXT_CONTINUE_CHECKING_TYPEKEY 61539
#define IDS_TTL_MEMORY_EXHAUSTED        61540
#define IDS_TXT_MEMORY_EXHAUSTED        61541
#define IDS_TTL_FAILURE_GET_BOOKMARK_INFO 61542
#define IDS_TXT_FAILURE_GET_BOOKMARK_INFO 61543
#define IDS_TTL_CONTINUE_PUTTING_BOOKMARKS 61544
#define IDS_TXT_CONTINUE_PUTTING_BOOKMARKS 61545
#define IDS_TXT_CONTINUE_PUTTING_BOOKMARK_INFO 61546
#define IDS_TTL_CONTINUE_ANALYSING      61547
#define IDS_TXT_CONTINUE_ANALYSING      61548
#define IDS_TTL_GETTING_BOOKMARK_USERS  61549
#define IDS_TXT_GETTING_HATENA_USERS    61550
#define IDS_TXT_GETTING_DELICIOUS_USERS 61551
#define IDS_TXT_GETTING_MMMEMO_USERS    61552
#define IDS_TXT_GETTING_ECNAVI_USERS    61553
#define IDS_TTL_URL_CHECK_RESULT        61554
#define IDS_TXT_INVALID_URL             61555
#define IDS_TXT_ADD_COLLECTON           61556
#define IDS_TXT_TEMPORARY_OFF           61557
#define IDS_TTL_UNSETTING               61558
#define IDS_TXT_UNSETTING               61559
#define IDS_TTL_CONTINUE_GETTING_TITLE  61560
#define IDS_TXT_CONTINUE_GETTING_TITLE  61561
#define IDS_TTL_BUSY_GETTING            61562
#define IDS_TXT_BUSY_GETTING            61563
#define IDS_TXT_BUSY_BUSY               61564
#define IDS_TXT_CONTINUE_PROCEEDING     61565
#define IDS_TTL_CONTINUE_GET_TAG_LIST   61566
#define IDS_TXT_CONTINUE_GET_TAG_LIST   61567
#define IDS_TTL_CONTINUE_DELETE_TAGS    61568
#define IDS_TXT_CONTINUE_DELETE_TAGS    61569
#define IDS_TTL_CONTINUE_REPLACE_TAGS   61570
#define IDS_TXT_CONTINUE_REPLACE_TAGS   61571
#define IDS_TXT_GETTING_LIVEDOORCLIP_USERS 61572
#define IDS_TXT_GETTING_DIGG_USERS      61573
#define IDS_TXT_TEMPORARY_ON            61574
#define IDS_TTL_GETTING_NUM_OF_STARS    61575
#define IDS_TXT_GETTING_HATENA_STAR_USERS 61576
#define IDS_TXT_GETTING_NIFTYCLIP_USERS 61577
#define IDS_URL_NIFTYCLIP               61578
#define IDS_ACCESSTOKEN_ACQUIRED        61579
#define IDS_ACCESSTOKEN_UNTAKEN         61580
#define IDS_TXT_TWITTER_STOP_OAUTH      61581
#define IDS_TXT_TWITTER_ALLOW_OAUTH     61582
#define IDS_TXT_SELECT_BLOG             61583
#define IDS_TTL_SELECT_BLOG             61584
#define IDS_DEFAULT_TARGET              61585
#define IDS_TXT_INPUT_PIN               61586
#define IDS_TTL_INPUT_PIN               61587

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        193
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1164
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
